# Site settings
title: Saatchi Guitar Gallery

email: arash.saatchi@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Saatchi specializes in hand made guitars. Other offerings contain
  private and group guitar lessens and ...

  <br/>
  Copyright (c) 2015 all rights reserved for Saatchi Guitar
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

baseurl: "/saatchi" # the subpath of your site, e.g. /blog/

url: "http://naghavi.me" # the base hostname & protocol for your site

twitter_username: saatchiguitar

github_username:  saatchiguitar

# Build settings
markdown: kramdown
